#!/usr/bin/env zsh

# KAT
# ===

# build the file `kat.k` from `KAT.md`
pandoc-tangle --from markdown --to code-k --code kat KAT.md > kat.k

# IMP-KAT
# =======

# build the files `imp.k` and `imp-kat.k` from `IMP-KAT.md`
pandoc-tangle --from markdown --to code-k --code imp-kat  KAT-IMP.md > imp-kat.k
pandoc-tangle --from markdown --to code-k --code imp-lang KAT-IMP.md > imp.k

# Kompile
# =======

# echo "kompiling ..."
# kompile --debug --main-module IMP-ANALYSIS --syntax-module IMP-ANALYSIS imp-kat.k || exit 1

# Examples
# ========

examples=(straight-line-1 straight-line-2 dead-if sum sum-plus collatz)

for example in $examples; do
    pandoc-tangle --from markdown --to code-k --code "$example" KAT-IMP-examples.md > "tests/$example.imp"
done

# Tests
# =====

pandoc-tangle --from markdown --to code-sh --code runtests KAT-IMP-examples.md > tests/runtests.sh
chmod u+x tests/runtests.sh

tests=( straight-line-1-bimc1 straight-line-1-bimc2
        straight-line-2-bimc1 straight-line-2-bimc2 straight-line-2-bimc3
        sum-bimc1 sum-bimc2 sum-bimc3
        collatz-bimc1 collatz-bimc2 collatz-bimc3
        straight-line-1-sbc straight-line-2-sbc
        dead-if-sbc sum-sbc sum-plus-sbc
        collatz-sbc
      )

for test in $tests; do
    pandoc-tangle --from markdown --to code-k --code "$test" KAT-IMP-examples.md > tests/output/$test.out
done


# echo "running tests ..."
# cat tests/runtests-outpu | grep -v -e '^//' -e '^$' | tr -squeeze-repeats ' '
