#!/usr/bin/env bash

exit_status='0'

runtest() {
    local test_file test_hash_orig test_hash_exec
    test_file="$1"      ; shift
    test_hash_orig="$1" ; shift
    test_hash_exec="$1" ; shift
    ./kat test "$test_file" "$test_hash_orig" "$test_hash_exec" || exit_status="$?"
}

runtest tests/fun/ackermann.fun                   103a032a87e4855ba91fe5b5c9b52a7b b63045261cd1eab797e2efc2d09804c2
# infinite loop
# runtest tests/fun/collatz-all-upto.fun          d1d56e40ca7ba4869e2be56f05d15ce6 xxx
runtest tests/fun/constructor-bst-sorting.fun     5cf50a61d7a350beb9b4a1c99f20e2ab 2e9aa3cb0dcbd492c2af11088502caeb
runtest tests/fun/constructor-tree-mirror.fun     5d5282b1a5eb1e1cc831889fe5d64a56 767c35265175b1d82bb312e6d7fd87c7
runtest tests/fun/empty-argument.fun              8c375a6f1820372c6cc32b84e2740ccd e1d24c4c1a8155730194e5b3e3835e2b
runtest tests/fun/exceptions-branch.fun           062736d4f769b6778384db923a26b75c 0029b082f4957ac57af4dd68deceb43d
runtest tests/fun/exceptions-branch-shadowing.fun bf0999071053e8106d89e049df42c545 d98371e066f2de30604a809e882a6e4b
runtest tests/fun/exceptions.fun                  10931e126aa8637b065c958b85ccb6e5 xxx
runtest tests/fun/exceptions-simple.fun           ecd3ab88dd726d28ef8a2a53e686eb6b xxx
runtest tests/fun/factorial-and-list-max.fun      fb5f3ffe3c0109d330feb4418746e5b2 xxx
runtest tests/fun/fold.fun                        1316d3231846a76625b4bc560f3ac758 xxx
runtest tests/fun/fold-sum.fun                    ea64bc2af98d82589b9db650b2a152d1 xxx
runtest tests/fun/fold-tree.fun                   107ca787401bcadbfb24c00c8268d0a9 xxx
runtest tests/fun/list-1.fun                      3ef41d1fa0266af816cd5dbb1507760d xxx
runtest tests/fun/list-2.fun                      b406b72ccca0b381ce5bc86333a63249 xxx
runtest tests/fun/list-match.fun                  38be5f602078ff8ea7da583fb2711b4a xxx
runtest tests/fun/list-max.fun                    086f61a3292db6b68d973e3df4aaaf5b xxx
runtest tests/fun/long-loop.fun                   6e2cb3e9cbf9b8460ccaa7c5ae7d8188 xxx
runtest tests/fun/map.fun                         35f2c2feaf21c2c6318079dc991badcd xxx
runtest tests/fun/non-linear-pattern.fun          0c3192aac4e49aed27747a1841abd3f0 xxx
runtest tests/fun/nth.fun                         f80031255e5d68b545ac4e0d6a101286 xxx
runtest tests/fun/partial-application.fun         c585e314c5830ac3ef8da011a5701dec xxx
runtest tests/fun/pattern-failure.fun             d94d7cd6375326340309c673fe4c0cb1 xxx
runtest tests/fun/pattern.fun                     0bde5e8afc94f1a16f623d46dc239c1d xxx
runtest tests/fun/pattern-simple.fun              3b58b41549dedb7070f3f31e115b04a9 xxx
runtest tests/fun/polymorphism-1.fun              7f1a30162d10027c5dc96867c50735cb xxx
runtest tests/fun/polymorphism-2.fun              d89a2c547d87a9b3f7ccdfad34c324cb xxx
runtest tests/fun/polymorphism-3.fun              b5a729c9b23883a5eaf46c8d0f91fffb xxx
runtest tests/fun/prelude.fun                     a8cab1aa7432c7f710a7dee46282d786 xxx
runtest tests/fun/references-1.fun                6533d8b5921c87787933085e13f6339d xxx
runtest tests/fun/references-2.fun                7e087b171a69092e3fc630afeaece4a0 xxx
runtest tests/fun/references-3.fun                e4055be648a775a273b48297c543882f xxx
runtest tests/fun/references-4.fun                a769758a875288268478418d913c4c05 xxx
runtest tests/fun/references-5.fun                7253969e7627926c1e92cccc4572a208 xxx
runtest tests/fun/simple-application.fun          e0ec3580a4d5bf4e6cec120ce09c73fb xxx
runtest tests/fun/simple-case.fun                 7587f7dd9bf78bb90aaba90113ffaaf7 xxx
runtest tests/fun/simple-case-letrec.fun          40f8dc34adfbb9ebfa36f8eb8b6b5c42 xxx
runtest tests/fun/simple-list.fun                 b8884415b7ff0f40d2288ad5379cca73 xxx
runtest tests/fun/sum.fun                         462f9bc25a799532d44dd93dd10c44bb xxx
runtest tests/fun/sum-tail-recursive.fun          81ed5d115b043ae2b448476b8732aab6 xxx
runtest tests/fun/tail-recursion.fun              0dfb92d3b508f3998c5351926857fccd xxx
runtest tests/fun/tuple-1.fun                     db4c0e2f2c6209d2cea8f9fafa243305 xxx
runtest tests/fun/tuple-2.fun                     5bed64a6d2c42dac3d71676a63f7130d xxx
runtest tests/fun/tuple-3.fun                     6c0d791c73660d0e37b509ef65f491f0 xxx

exit "$exit_status"
